services:
  load-balancer:
    image: haproxy:3.2
    container_name: haproxy
    ports:
      - "8080:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nginx-a
      - nginx-b
    restart: unless-stopped

  # ----------Nginx containers for load balancing

  nginx-a:
    image: nginx:latest
    container_name: nginx-a
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
      - service2
      - service3
      - service4
      - service5
      - service6
    restart: unless-stopped

  nginx-b:
    image: nginx:latest
    container_name: nginx-b
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
      - service2
      - service3
      - service4
      - service5
      - service6
    restart: unless-stopped

  # ----------Nginx containers for load balancing

  # ----------services containers for load balancing

  service1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-service-1
    environment:
      PORT: 3001
      SERVICE_NAME: "Service 1"
    expose:
      - "3001"
    restart: unless-stopped

  service2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-service-2
    environment:
      PORT: 3002
      SERVICE_NAME: "Service 2"
    expose:
      - "3002"
    restart: unless-stopped

  service3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-service-3
    environment:
      PORT: 3003
      SERVICE_NAME: "Service 3"
    expose:
      - "3003"
    restart: unless-stopped

  service4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-service-4
    environment:
      PORT: 3004
      SERVICE_NAME: "Service 4"
    expose:
      - "3004"
    restart: unless-stopped

  service5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-service-5
    environment:
      PORT: 3005
      SERVICE_NAME: "Service 5"
    expose:
      - "3005"
    restart: unless-stopped

  service6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-service-6
    environment:
      PORT: 3006
      SERVICE_NAME: "Service 6"
    expose:
      - "3006"
    restart: unless-stopped
