events {
    worker_connections 1024;
}

http {
    upstream backend {
        #  NGINX hash load balancing method
        # hash $request_uri consistent;

        # Least connections load balancing method
        # least_conn; 

        # least_time load balancing method
        
        # least_time header;	    # Time until response headers arrive
        # least_time last_byte;  	  # Time until the complete response arrives
        # least_time last_byte inflight;	# Also accounts for requests still in progress

        # Round-robin load balancing
        # server service1:3001;
        # server service2:3002;
        # server 10.238.144.220:3000; 
        # AWS EC2 service
        # server 13.234.xxx.xxx:3000;

        # Weighted load balancing
        # server service1:3001 weight=3;
        # server service2:3002 weight=2;
        # server 192.168.1.8:3000 weight=1;

        # -----------health check and failover-------
        # server service1:3001 max_fails=3 fail_timeout=30s;    
        zone backend 64k;

        least_conn;
        server service1:3001 max_fails=1 fail_timeout=10s;
        server service2:3002 max_fails=1 fail_timeout=10s;
        server 192.168.1.8:3000 max_fails=1 fail_timeout=10s;

    }

 
    server {
        listen 80;

         # Health endpoint for Nginx itself
        location = /health {
            default_type application/json;
            add_header Cache-Control "no-store" always;

            return 200 '{"status":"ok","service":"nginx"}\n';
        }

        location / {
           proxy_pass http://backend;

        # -----------health check and failover-------

            proxy_connect_timeout 2s;
            proxy_send_timeout 5s;
            proxy_read_timeout 5s;

            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_next_upstream_tries 3;
            proxy_next_upstream_timeout 10s;


        # --------- active health_check is only available in NGINX Plus ----------------
            # proxy_connect_timeout 2s;
            # proxy_read_timeout 5s;

            # health_check
            #     uri=/health
            #     interval=5s
            #     fails=2
            #     passes=2
            #     mandatory
            #     match=healthy_response;
        # -----------health check and failover-------

            # for see the upstream server address in the response header
            add_header X-Backend $upstream_addr always;
            add_header X-Backend-Status $upstream_status always;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /nginx_status {
            stub_status;
        }
    }
}