events {
    worker_connections 1024;
}

http {
    upstream backend {
        #  NGINX hash load balancing method
        # hash $request_uri consistent;

        # Least connections load balancing method
        least_conn;

        # Round-robin load balancing
        server service1:3001;
        server service2:3002;
        server 10.238.144.220:3000; 
        # AWS EC2 service
        # server 13.234.xxx.xxx:3000;

        # Weighted load balancing
        # server service1:3001 weight=3;
        # server service2:3002 weight=2;
        # server 192.168.1.8:3000 weight=1;
    }

 
    server {
        listen 80;

         # Health endpoint for Nginx itself
        location = /health {
            default_type application/json;
            add_header Cache-Control "no-store" always;

            return 200 '{"status":"ok","service":"nginx"}\n';
        }

        location / {
           proxy_pass http://backend;

            # for see the upstream server address in the response header
            add_header X-Backend $upstream_addr always;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /nginx_status {
            stub_status;
        }
    }
}